### ISSUE TITLE
Checklist for 1.0

### ISSUE THREAD

**Issue by ryanmrichard** [pulsar-chem/Pulsar-Core#16]
#Documentation
   - [ ] How to build systems
   - [ ] How to use integrals
   - [ ] Ensure each class is documented
#Tests
   - [ ] Unit tests for all classes (both Python and C interfaces)
   - [ ] Acceptance tests (? may be better as a StandardModules milestone)
   - [ ] Travis-CI
   - [ ] Code coverage
#Code
   - [ ] Clean-up System folder (symmetry stuff in terms of Eigen)
   - [ ] Clean-up Math folder (get rid of stuff handled by Eigen)
